//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch HPetriSim.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    103
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 104
#define CG_IDS_PHYSICAL_MEM             105
#define CG_IDS_DISK_SPACE               106
#define CG_IDS_DISK_SPACE_UNAVAIL       107
#define IDS_AUTHOR                      108
#define IDD_PROPPAGE1                   109
#define IDS_SOFTWARE                    109
#define IDD_PROPPAGE2                   110
#define IDS_COPYRIGHT                   110
#define IDD_PROPPAGE3                   111
#define IDS_URL                         111
#define IDS_PROPSHT_CAPTION1            112
#define CG_ID_VIEW_MYDIALOGBAR          116
#define CG_IDD_MYDIALOGBAR              117
#define IDS_LIC_URL                     118
#define CG_IDS_PROGRESS_CAPTION         120
#define CG_IDD_PROGRESS                 121
#define ID_INDICATOR_STEPTIME           125
#define ID_INDICATOR_SIMSTATUS          126
#define ID_INDICATOR_SIMTIME            127
#define IDR_MAINFRAME                   128
#define IDR_HPSTYPE                     129
#define IDR_EDITBAR                     130
#define ID_INDICATOR_COUNT              131
#define ID_INDICATOR_MOUSEPOS           133
#define ID_INDICATOR_ZOOMSCALE          134
#define ID_SLIDER_SIMSPEED              136
#define IDR_SYMBAR                      137
#define ID_SIM_RESET                    138
#define IDR_SYM_VIEW                    139
#define ID_PAUSE_MODE                   140
#define IDR_SYM_OUTPUT_VIEW             141
#define ID_SPEED_MODE                   142
#define IDD_SYM_LOG_DIALOG              143
#define IDS_FIRMA                       143
#define IDD_TRANSITION_DIALOG           144
#define IDR_HPS_OUTPUT                  144
#define IDD_SYM_DIALOG                  145
#define IDD_POSITION_DIALOG             146
#define IDD_TEXT_DIALOG                 147
#define IDD_LABEL_DIALOG                148
#define IDD_PROPPAGE4                   149
#define IDD_PROPPAGE5                   150
#define IDR_MAINBAR                     151
#define IDS_ERROR_FILE_OPEN             152
#define IDD_SYMSTATE_VIEW               153
#define IDS_ERROR_INIT_NET              153
#define IDS_ERROR_MEMORY                154
#define IDS_ERROR_CONN_D                155
#define IDS_ERROR_CONN_A                156
#define IDB_EDITBAR                     157
#define IDS_ERROR_CONN_B                157
#define IDS_ERROR_CONN_C                158
#define IDC_POSITION                    162
#define IDC_TRANSITION                  163
#define IDC_POLYGON                     164
#define IDC_CONNECTOR                   165
#define IDC_LINE                        167
#define IDC_TEXT                        168
#define IDC_RECT                        169
#define IDC_ZOOMIN                      170
#define IDC_ZOOMOUT                     171
#define IDC_PAN_RIGHT                   174
#define IDC_PAN_ALL                     175
#define IDC_PAN_DOWN                    176
#define IDC_PAN_LEFT                    177
#define IDC_PAN_UP                      178
#define IDB_AUTOPAN                     179
#define IDD_LIMIT_DIALOG                181
#define IDS_LIMIT_TEXT                  182
#define IDS_ABOUT_TEXT                  183
#define IDS_MEM_TEXT                    184
#define IDS_EMAIL                       185
#define IDS_MAILTO                      185
#define IDS_ABOUT_LIMIT                 186
#define IDS_SERIAL_NUMBER               187
#define IDS_FILE_CHECKSUM               188
#define IDB_PLACE_25                    190
#define IDB_PLACE_15                    192
#define IDB_PLACE_20                    195
#define IDB_PLACE_35                    196
#define IDB_PLACE_50                    197
#define IDR_TOOLBAR1                    200
#define IDB_BITMAP1                     201
#define IDR_MAINFRAME_256               202
#define IDR_EDITBAR_256                 203
#define IDR_SYMBAR_256                  204
#define IDR_OUTPUT_POPUP                205
#define IDR_SIMBAR                      206
#define IDR_SIMBAR_256                  207
#define ID_UPDATE_PROPERTYS             471
#define ID_INDICATOR_STEPCOUNT          472
#define IDS_TOOLBAR_STANDARD            473
#define ID_VIEW_OUTPUTWND               473
#define IDS_TOOLBAR_CUSTOMIZE           474
#define ID_OBJECT_PROPERTYS             474
#define IDS_TOOLBAR_EDIT                475
#define ID_VIEW_PROPERTIESWND           475
#define IDS_TOOLBAR_SIM                 476
#define ID_VIEW_CUSTOMIZE               476
#define IDS_OUTPUT_WND                  477
#define ID_WINDOW_MANAGER               477
#define IDS_PROPERTIES_WND              478
#define IDS_WINDOWS_MANAGER             479
#define CG_IDC_PROGDLG_PROGRESS         1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_SYM_LOG_EDIT                1007
#define IDC_SCAN_TIME_EDIT              1009
#define IDC_LOOPS_EDIT                  1010
#define IDC_INMEDIATE_RADIO             1011
#define IDC_DELAY_ON_RADIO              1012
#define IDC_DELAY_ON_EDIT               1015
#define IDC_DELAY_OFF_RADIO             1016
#define IDC_IGNORE_RADIO                1016
#define IDC_DELAY_OFF_EDIT              1017
#define IDC_FIRST_RADIO                 1017
#define IDC_RAND_RADIO                  1018
#define IDC_RAND_OFF_RADIO              1018
#define IDC_RAND_OFF_EDIT               1019
#define IDC_RAND_ON_RADIO               1020
#define IDC_RAND_ON_EDIT                1021
#define IDC_AUTO_CHECK                  1022
#define IDC_TIMER_STOP_CHECK            1023
#define IDC_DELAY_TOKEN_RADIO           1023
#define IDC_RAND_TOKEN_RADIO            1024
#define IDC_NEVER_TOKEN_RADIO           1025
#define IDC_START_TOKEN_RADIO           1026
#define IDC_RESTART_CHECK               1027
#define IDC_TEXT_EDIT                   1027
#define IDC_GRIDVISIBLE_CHECK           1030
#define IDC_NETOBJECTS_CHECK            1038
#define IDC_DRAWOBJECTS_CHECK           1039
#define IDC_GRID_EDIT                   1041
#define IDC_GRID_SPIN                   1042
#define IDC_HOR_EDIT                    1043
#define IDC_VER_EDIT                    1044
#define IDC_EDIT1                       1054
#define IDC_EDIT_MEM                    1054
#define IDC_EDIT2                       1055
#define IDC_EDIT_LIMITTEXT              1055
#define IDC_EDIT_ABOUT                  1055
#define IDC_PROGRESS_LOAD               1057
#define IDC_SLIDER_SPEED                1058
#define IDC_PHYSICAL_MEM                1059
#define IDC_PHYSICAL_MEM_LOAD           1061
#define IDC_PHYSICAL_MEM_FREE           1062
#define IDC_PHYSICAL_MEM_PAGEFILE       1063
#define IDC_PHYSICAL_MEM_PAGEFILE_FREE  1064
#define IDC_PHYSICAL_MEM_VIRTUAL        1065
#define IDC_PHYSICAL_MEM_VIRTUAL_FREE   1066
#define IDC_LIST_ENUM_DRIVES            1067
#define IDC_EDIT_STOP_SIMULATIONTIME    1069
#define IDC_EDIT_SAMPLETIME             1070
#define IDC_EDIT_STOP_SIMULATIONTIME2   1071
#define IDC_EDIT_OUTPUT_FILE            1072
#define IDC_BUTTON_FILEDIALOG           1073
#define IDC_BUTTON_BACKCOLOR            1074
#define IDC_CHECK_POPMESSAGE            1075
#define IDC_CHECK_POPEXPLORER           1076
#define IDC_HYPERLINK                   1076
#define IDC_STATIC_SERIAL               1077
#define IDC_STATIC_AUTHOR               1078
#define IDC_STATIC_SOFTWARE             1079
#define IDC_BUTTON_MAILTO               1080
#define IDC_STATIC_COPYRIGHT            1081
#define IDC_BUTTON_URL                  1082
#define IDC_BUTTON_URL2                 1083
#define IDC_BUTTON_LIC_URL              1083
#define ID_RECT_MODE                    32774
#define ID_LINE_MODE                    32775
#define ID_SELECT_MODE                  32776
#define ID_VIEW_SYM                     32777
#define ID_POSITION_MODE                32780
#define ID_TRANSITION_MODE              32781
#define ID_MULTI_LINE_MODE              32782
#define ID_CONNECTOR_MODE               32783
#define ID_TEXT_MODE                    32784
#define ID_STOP_MODE                    32785
#define ID_STEP_MODE                    32786
#define ID_SYM_MODE                     32787
#define ID_RUN_MODE                     32788
#define ID_SYM_PROPERTYS                32790
#define ID_ZOOM_IN                      32794
#define ID_VIEW_SYM_OUTPUT              32795
#define ID_ZOOM_NORM                    32797
#define ID_ZOOM_OUT                     32798
#define ID_ZOOM_PORT                    32799
#define ID_RECT_BORDERCOLOR             32800
#define ID_RECT_FILLCOLOR               32801
#define ID_CONTEXT_BORDERCOLOR          32802
#define ID_CONTEXT_COMMAND1             32803
#define ID_CONTEXT_COMMAND2             32804
#define ID_CONTEXT_COMMAND3             32805
#define ID_CONTEXT_COMMAND4             32806
#define ID_CONTEXT_COMMAND5             32807
#define ID_CONTEXT_COMMAND6             32808
#define ID_CONTEXT_COMMAND7             32809
#define ID_CONTEXT_COMMAND8             32810
#define ID_CONTEXT_COMMAND9             32811
#define ID_CONTEXT_COMMAND10            32812
#define ID_CONTEXT_COMMAND11            32813
#define ID_CONTEXT_COMMAND12            32814
#define ID_CONTEXT_COMMAND13            32815
#define ID_CONTEXT_COMMAND14            32816
#define ID_CONTEXT_COMMAND15            32817
#define ID_CONTEXT_COMMAND16            32818
#define ID_CONTEXT_COMMAND17            32819
#define ID_CONTEXT_COMMAND18            32820
#define ID_CONTEXT_COMMAND19            32821
#define ID_CONTEXT_COMMAND20            32822
#define ID_CONTEXT_POPUP                32823
#define ID_CONTEXT_PUSHBACK             32824
#define ID_GROUP                        32825
#define ID_UNGROUP                      32826
#define ID_EDITOR_EIGENSCHAFTEN         32827
#define ID_EDITOR_PROPERTIES            32828
#define ID_EDITOR_SHOWLABEL             32829
#define ID_SYM_SINGLESTEP               32830
#define ID_SYM_RUNNORMAL                32831
#define ID_SYM_RUNFAST                  32832
#define ID_SYM_STOP                     32833
#define ID_SYM_RESET                    32834
#define ID_SYM_INCREASESPEED            32835
#define ID_SYM_DECREASESPEED            32837
#define ID_STORE_SCREEN                 32862
#define ID_STORE_CLIENT                 32863
#define ID_ENABLE_WRITEOUTPUTFILE       32864
#define ID_FILE_EXPORT_NET              32865
#define ID_FILE_EXPORT_INTERCHANGE      32866
#define ID_FILE_IMPORT_INTERCHANGE      32867
#define ID_REMOVE_SELECTED              32868
#define ID_PAN_MODE                     32869
#define ID_POPUP_KOPIEREN               32870
#define ID_POPUP_1                      32871
#define ID_                             32872
#define ID_POPUP_HIDE                   32873
#define IDR_TOOLBAR                     32874
#define ID_TOOLBARSANDDOCKINGWINDOWS_   32875
#define ID_BUTTON32879                  32879

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32880
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           478
#endif
#endif
